### ISSUE TITLE
wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by eitch** [Pi4J/pi4j-example-javafx#1]
After running `mvn clean package` on a 32-bit Raspberry Pi OS, and starting the application i get the following:

```
OpenJDK Server VM warning: You have loaded library /home/pi/.openjfx/cache/15.0.1/libprism_es2.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /home/pi/.openjfx/cache/15.0.1/libprism_es2.so: /home/pi/.openjfx/cache/15.0.1/libprism_es2.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
java.lang.UnsatisfiedLinkError: /home/pi/.openjfx/cache/15.0.1/libprism_es2.so: /home/pi/.openjfx/cache/15.0.1/libprism_es2.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at javafx.graphics/com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:214)
	at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:194)
	at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:135)
	at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:53)
	at javafx.graphics/com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:69)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:51)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at javafx.graphics/com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)

```

**Comment by eitch** [comment]
This was done on a Raspberry 3 CrowPi setup

**Comment by FDelporte** [comment]
Investigating...
* Full OS 32-bit with JavaFX 16
   * Starting in VSC with "Run" on main method = GUI starts but indeed throws "wrong ELF class: ELFCLASS64"
   * Starting from terminal with "cd target/distribution ; sudo ./run.sh" = idem
* Lite OS 32-bit with JavaFX 17
   * Could not successfully start yet, GUI not shown, same ELF error.

**Comment by FDelporte** [comment]
Different messages resulting in the same error in the logs

/root/.openjfx/cache/15.0.1/libprism_es2.so
/root/.openjfx/cache/15.0.1/libprism_sw.so
/root/.openjfx/cache/15.0.1/libglass.so

**Comment by FDelporte** [comment]
Problem is clear: javafx15-jars in target/distribution from maven dependencies are 64bit and conflicting with the ones which should be loaded from Gluon JavaFX for Raspberry Pi.

Still need to check what is best approach to not have them in the build directory.

**Comment by FDelporte** [comment]
fix in commit https://github.com/Pi4J/pi4j-example-javafx/commit/9d15bb8463184244e5d3aad39aa1363be84fded1

added to pom.xml: <excludeGroupIds>org.openjfx</excludeGroupIds>
